# Generated by Django 3.0 on 2019-12-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_db', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Belonging',
        ),
    ]
